<?php

/**
 * Implementation of hook_block()
 */

function foodisfree_blocks_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list':
      $blocks['donate']['info'] = t('Donate');
      $blocks['donate']['cache'] = BLOCK_NO_CACHE;


      return $blocks;
    case 'view':
      switch($delta) {
    case 'donate':
      $block['content'] = theme('donate', menu_get_object('node'));
    break;

      }
      return $block;
    case 'configure':

    case 'save':

  }
}

function foodisfree_blocks_theme($existing, $type, $theme, $path) {
  return array(
    'donate' => array(
      'arguments' => array('node' => null),
      'template' => 'block-donate',
    ),
  );
}