<?php
/**
 * Implements hook_block_info().
 */
function foodisfree_blocks_block_info() {
  $blocks['donate'] = array(
    'info' => t('Donate'),
    'status' => TRUE,
    'region' => 'content',
    'weight' => 0,
    'visibility' => 0,
    'pages' => 'admin*
coder*
node/add*
node/*/edit
node/*/devel
',
  );

  return $blocks;
}
  
/**
  * Implements hook_block_view().
  */
function foodisfree_blocks_block_view($delta='') {
  $block = array();

  switch ($delta) {
    case 'donate':
      $block['subject'] = t('Donate');
      $block['content'] = donate_contents();
      break;
  }
  
  return $block;
}

/**
 * custom html block
 * @return string
 */
function donate_contents() {
  return '
   <h1>Donate!</h1>
  ';
}
?>