<?php
/**
 * Implements hook_block_info().
 */
function foodisfree_blocks_block_info() {
  $blocks['donate'] = array(
    'info' => t('Donate'),
    'status' => TRUE,
    'region' => 'content',
    'weight' => 0,
    'visibility' => 0,
    'pages' => 'admin*
coder*
node/add*
node/*/edit
node/*/devel
',
  );

  return $blocks;
}
  
/**
  * Implements hook_block_view().
  */
function foodisfree_blocks_block_view($delta='') {
  $block = array();

  switch ($delta) {
    case 'donate':
      $block['subject'] = t('Donate');
      $block['content'] = donate_contents();
      break;
  }
  
  return $block;
}

/**
 * custom html block
 * @return string
 */
function donate_contents() {
  return '
    <div class="message">We\'re a non-profit, so any donation you make would be awesome!</div>
    <div class="form">
      <div class="input">$ <input type="textbox"/></div>
      <div class="nextButton"><span>NEXT</span><span class="icon"></span></div>
    </div>
    <div class="message-bottom">
      <div class="heading">No money? No worries!</div>
      We\'ll also take compost, soil, and other materials.
      <a href="#">Let us know what you\'ve got<a>
    <div>
  ';
}
?>